### ISSUE TITLE
Some pictures where gifs are supposed to be have words on them, not sure if I'm still supposed to cover them up

### ISSUE THREAD

**Issue by tosbey1** [tosbey1/random_tasks#1]
@bbertucc 
https://github.com/tosbey1/random_tasks/tree/master/Book_js_app

**Comment by bbertucc** [comment]
Just keep a running log of the pictures that cover up text here and I'll fix 'em.

**Comment by tosbey1** [comment]
Living Concept art/simple plug_v01-smaller.gif
Living Concept art/Stem 1_v02 gradient.gif

**Comment by bbertucc** [comment]
Would you mind jumping on this issue @tosbey1? 

What you can probably to.. Import the page into illustrator.. Erase the area with the GIF.. Save the image as a PNG.. Lay that PNG over the GIF..

**Comment by bbertucc** [comment]
Never mind .. I'll get to this one..

**Comment by bbertucc** [comment]
Done!
